### ISSUE TITLE
Flascc compiler error? (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by racingpht** [adobe/glsl2agal#15]
Hi, we are able to use glsl2agal in our as3-only project. But when we want to link with flascc code, compiling fails:

java.lang.NullPointerException
        at com.adobe.flash.compiler.internal.scopes.ASProjectScope.getCompilationUnitForDefinition(ASProjectScope.java:1358)
        at com.adobe.flash.compiler.internal.scopes.ASProjectScope.removeDefinition(ASProjectScope.java:1123)

...(detailed error list can be seen here as well: http://forums.adobe.com/thread/1134928)

Could you give us some ideas?
Thanks very much!

**Comment by alexmac** [comment]
I've answered this in the original thread now, but to summarise: asc2 isn't designed to be used this way, what you really want to do is link the bitcode into your FlasCC app.
